package unarr

/*
#include "external/lzma/7zBuf.c"
#include "external/lzma/7zDec.c"
#include "external/lzma/7zIn.c"
#include "external/lzma/7zStream.c"
#include "external/lzma/Bcj2.c"
#include "external/lzma/Bra.c"
#include "external/lzma/Bra86.c"
#include "external/lzma/LzmaDec.c"
#include "external/lzma/Lzma2Dec.c"

#include "external/zlib/adler32.c"
#include "external/zlib/crc32.c"
#include "external/zlib/inffast.c"
#include "external/zlib/inflate.c"
#include "external/zlib/inftrees.c"
#include "external/zlib/zutil.c"

#include "external/bzip2/blocksort.c"
#include "external/bzip2/bzlib.c"
#include "external/bzip2/compress.c"
#include "external/bzip2/crctable.c"
#include "external/bzip2/decompress.c"
#include "external/bzip2/huffman.c"
#include "external/bzip2/randtable.c"

#include "external/unarr/common/conv.c"
#include "external/unarr/common/crc32.c"
#include "external/unarr/common/stream.c"
#include "external/unarr/common/unarr.c"
#include "external/unarr/lzmasdk/CpuArch.c"
#include "external/unarr/lzmasdk/Ppmd7.c"
#include "external/unarr/lzmasdk/Ppmd7Dec.c"
#include "external/unarr/lzmasdk/Ppmd8.c"
#include "external/unarr/lzmasdk/Ppmd8Dec.c"
#include "external/unarr/rar/filter-rar.c"
#include "external/unarr/rar/parse-rar.c"
#include "external/unarr/rar/rar.c"
#include "external/unarr/rar/rarvm.c"
#include "external/unarr/rar/uncompress-rar.c"
#include "external/unarr/rar/huffman-rar.c"
#include "external/unarr/zip/parse-zip.c"
#include "external/unarr/zip/uncompress-zip.c"
#include "external/unarr/zip/zip.c"
#include "external/unarr/_7z/_7z.c"
#include "external/unarr/tar/tar.c"
#include "external/unarr/tar/parse-tar.c"
#include "external/unarr/zip/inflate.c"

#cgo !debug CFLAGS: -DNDEBUG
#cgo CFLAGS: -DHAVE_7Z -DHAVE_ZLIB -DHAVE_BZIP2 -D_7ZIP_PPMD_SUPPPORT -Iexternal/lzma -Iexternal/zlib -Iexternal/bzip2 -Iexternal/unarr -pipe -O3 -fomit-frame-pointer
*/
import "C"
